### ISSUE TITLE
添加不存在的块ID时，无法删除

### ISSUE THREAD

**Issue by pureTrue** [zuoez02/siyuan-plugin-docky#10]
不小心点到+号之后，因为剪贴板并不是块ID名，所以添加了一个无限加载的页面，右上角也没有删除按钮……
@zuoez02

**Comment by zuoez02** [comment]
找到你工作空间里data\storage\petal\siyuan-plugin-docky\config.json这个文件，手动删除掉你的那个粘贴的东西，前提是你懂JSON
________________________________
发件人: Pz ***@***.***>
发送时间: 2024年5月27日 10:52
收件人: zuoez02/siyuan-plugin-docky ***@***.***>
抄送: Luto Yvan ***@***.***>; Mention ***@***.***>
主题: [zuoez02/siyuan-plugin-docky] 添加不存在的块ID时，无法删除 (Issue #10)


不小心点到+号之后，因为剪贴板并不是块ID名，所以添加了一个无限加载的页面，右上角也没有删除按钮……
@zuoez02<https://github.com/zuoez02>

―

**Comment by HaoCeans** [comment]
希望尽快增加删除按钮！！！非常需要

**Comment by zuoez02** [comment]
finished in v0.4.5
