### ISSUE TITLE
请问能否实现点击工具栏的块跳转到对应的笔记位置

### ISSUE THREAD

**Issue by dempsey-wen** [zuoez02/siyuan-plugin-docky#4]
有的时候想通过侧边工具栏回溯到工具块的上下文，没有回溯功能就只能够靠自己的记忆或者检索，因此希望能够添加点击工具栏的块或者某个按键，跳转到对应的笔记。

另外分享一下，结合“便利贴”插件可以将这个侧边工具栏当作工作空间的备忘便签使用，效果非常好。

**Comment by zuoez02** [comment]
0.4.3
