### ISSUE TITLE
新建工作空间后无法正常使用

### ISSUE THREAD

**Issue by litcu** [zuoez02/siyuan-plugin-docky#7]
新建一个工作空间，安装侧边栏插件，启用，没有在dock栏找到侧边栏面板。重启仍没有。其他插件正常。

![image](https://github.com/zuoez02/siyuan-plugin-docky/assets/153990846/a7096849-4ca9-47e7-ae08-005fa71dc6db)

**Comment by zuoez02** [comment]
修复于v0.4.2
